# Form implementation generated from reading ui file 'resources/rainbotGUI.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from rainbotgui.gui.resources import resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1034, 640))
        MainWindow.setBaseSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono,Helvetica")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainIcons/icons/rake.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(4, 4, 4);\n"
"    font-family: \"JetBrains Mono\", Helvetica;\n"
"    border-radius: 8px;\n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 500))
        self.centralwidget.setBaseSize(QtCore.QSize(1280, 720))
        self.centralwidget.setStyleSheet("color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headerBar = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerBar.sizePolicy().hasHeightForWidth())
        self.headerBar.setSizePolicy(sizePolicy)
        self.headerBar.setMinimumSize(QtCore.QSize(0, 24))
        self.headerBar.setMaximumSize(QtCore.QSize(16777215, 24))
        self.headerBar.setStyleSheet("border-radius: 0;\n"
"background-color: black;\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 8px;\n"
"")
        self.headerBar.setObjectName("headerBar")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.headerBar)
        self.horizontalLayout_6.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.status_bar = QtWidgets.QFrame(parent=self.headerBar)
        self.status_bar.setMinimumSize(QtCore.QSize(0, 24))
        self.status_bar.setMaximumSize(QtCore.QSize(16777215, 24))
        self.status_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.status_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.status_bar.setObjectName("status_bar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.status_bar)
        self.horizontalLayout_5.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.icon_lbl = QtWidgets.QLabel(parent=self.status_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_lbl.sizePolicy().hasHeightForWidth())
        self.icon_lbl.setSizePolicy(sizePolicy)
        self.icon_lbl.setMinimumSize(QtCore.QSize(24, 24))
        self.icon_lbl.setMaximumSize(QtCore.QSize(24, 24))
        self.icon_lbl.setText("")
        self.icon_lbl.setPixmap(QtGui.QPixmap(":/MainIcons/icons/rake.ico"))
        self.icon_lbl.setScaledContents(True)
        self.icon_lbl.setObjectName("icon_lbl")
        self.horizontalLayout_5.addWidget(self.icon_lbl)
        self.build_info = QtWidgets.QLabel(parent=self.status_bar)
        self.build_info.setMinimumSize(QtCore.QSize(50, 24))
        self.build_info.setStyleSheet("color: rgba(255,255,255,100);\n"
"\n"
"")
        self.build_info.setObjectName("build_info")
        self.horizontalLayout_5.addWidget(self.build_info, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_6.addWidget(self.status_bar, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.windowframe_btns = QtWidgets.QFrame(parent=self.headerBar)
        self.windowframe_btns.setMinimumSize(QtCore.QSize(150, 24))
        self.windowframe_btns.setMaximumSize(QtCore.QSize(150, 24))
        self.windowframe_btns.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.windowframe_btns.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.windowframe_btns.setObjectName("windowframe_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.windowframe_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimize_btn = QtWidgets.QPushButton(parent=self.windowframe_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimize_btn.sizePolicy().hasHeightForWidth())
        self.minimize_btn.setSizePolicy(sizePolicy)
        self.minimize_btn.setMinimumSize(QtCore.QSize(50, 24))
        self.minimize_btn.setMaximumSize(QtCore.QSize(50, 24))
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 30, 30);\n"
"}")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/MainIcons/icons/minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setIconSize(QtCore.QSize(22, 22))
        self.minimize_btn.setCheckable(False)
        self.minimize_btn.setAutoRepeat(False)
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout_4.addWidget(self.minimize_btn)
        self.fullscreen_btn = QtWidgets.QPushButton(parent=self.windowframe_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullscreen_btn.sizePolicy().hasHeightForWidth())
        self.fullscreen_btn.setSizePolicy(sizePolicy)
        self.fullscreen_btn.setMinimumSize(QtCore.QSize(50, 24))
        self.fullscreen_btn.setMaximumSize(QtCore.QSize(50, 24))
        self.fullscreen_btn.setStyleSheet("QPushButton{\n"
"border-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(30, 30, 30);\n"
"}")
        self.fullscreen_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/MainIcons/icons/select_fls.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.fullscreen_btn.setIcon(icon2)
        self.fullscreen_btn.setIconSize(QtCore.QSize(16, 16))
        self.fullscreen_btn.setCheckable(False)
        self.fullscreen_btn.setAutoRepeat(False)
        self.fullscreen_btn.setObjectName("fullscreen_btn")
        self.horizontalLayout_4.addWidget(self.fullscreen_btn)
        self.close_btn = QtWidgets.QPushButton(parent=self.windowframe_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setMinimumSize(QtCore.QSize(50, 24))
        self.close_btn.setMaximumSize(QtCore.QSize(50, 24))
        self.close_btn.setStyleSheet("QPushButton{\n"
"border-top-right-radius: 8px;\n"
"border-top-left-radius: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 0, 0);\n"
"}")
        self.close_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/MainIcons/icons/closeW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_btn.setIcon(icon3)
        self.close_btn.setIconSize(QtCore.QSize(20, 20))
        self.close_btn.setCheckable(False)
        self.close_btn.setAutoRepeat(False)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_4.addWidget(self.close_btn)
        self.horizontalLayout_6.addWidget(self.windowframe_btns)
        self.verticalLayout_3.addWidget(self.headerBar)
        self.bottonFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.bottonFrame.setObjectName("bottonFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottonFrame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftSide = QtWidgets.QFrame(parent=self.bottonFrame)
        self.leftSide.setMinimumSize(QtCore.QSize(300, 0))
        self.leftSide.setMaximumSize(QtCore.QSize(300, 16777215))
        self.leftSide.setStyleSheet("background-color: rgb(6,6,6);\n"
"border-radius: 8px;")
        self.leftSide.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.leftSide.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftSide.setObjectName("leftSide")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftSide)
        self.verticalLayout.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_btns = QtWidgets.QFrame(parent=self.leftSide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_btns.sizePolicy().hasHeightForWidth())
        self.left_btns.setSizePolicy(sizePolicy)
        self.left_btns.setMinimumSize(QtCore.QSize(280, 0))
        self.left_btns.setStyleSheet("border: none;")
        self.left_btns.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.left_btns.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.left_btns.setObjectName("left_btns")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_btns)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.terminal_btn = QtWidgets.QPushButton(parent=self.left_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal_btn.sizePolicy().hasHeightForWidth())
        self.terminal_btn.setSizePolicy(sizePolicy)
        self.terminal_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.terminal_btn.setMaximumSize(QtCore.QSize(280, 16777215))
        self.terminal_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.terminal_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.terminal_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/MainIcons/icons/terminalW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.terminal_btn.setIcon(icon4)
        self.terminal_btn.setIconSize(QtCore.QSize(32, 32))
        self.terminal_btn.setCheckable(True)
        self.terminal_btn.setChecked(False)
        self.terminal_btn.setObjectName("terminal_btn")
        self.leftButtons = QtWidgets.QButtonGroup(MainWindow)
        self.leftButtons.setObjectName("leftButtons")
        self.leftButtons.addButton(self.terminal_btn)
        self.verticalLayout_2.addWidget(self.terminal_btn)
        self.stats_btn = QtWidgets.QPushButton(parent=self.left_btns)
        self.stats_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.stats_btn.setMaximumSize(QtCore.QSize(280, 16777215))
        self.stats_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.stats_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/MainIcons/icons/statsW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stats_btn.setIcon(icon5)
        self.stats_btn.setIconSize(QtCore.QSize(32, 32))
        self.stats_btn.setCheckable(True)
        self.stats_btn.setAutoRepeat(False)
        self.stats_btn.setObjectName("stats_btn")
        self.leftButtons.addButton(self.stats_btn)
        self.verticalLayout_2.addWidget(self.stats_btn)
        self.logs_btn = QtWidgets.QPushButton(parent=self.left_btns)
        self.logs_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.logs_btn.setMaximumSize(QtCore.QSize(280, 16777215))
        self.logs_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logs_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/MainIcons/icons/logsW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logs_btn.setIcon(icon6)
        self.logs_btn.setIconSize(QtCore.QSize(32, 32))
        self.logs_btn.setCheckable(True)
        self.logs_btn.setObjectName("logs_btn")
        self.leftButtons.addButton(self.logs_btn)
        self.verticalLayout_2.addWidget(self.logs_btn)
        self.wbsocket_btn = QtWidgets.QPushButton(parent=self.left_btns)
        self.wbsocket_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.wbsocket_btn.setMaximumSize(QtCore.QSize(280, 16777215))
        self.wbsocket_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.wbsocket_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/MainIcons/icons/websocketW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.wbsocket_btn.setIcon(icon7)
        self.wbsocket_btn.setIconSize(QtCore.QSize(32, 32))
        self.wbsocket_btn.setCheckable(True)
        self.wbsocket_btn.setObjectName("wbsocket_btn")
        self.leftButtons.addButton(self.wbsocket_btn)
        self.verticalLayout_2.addWidget(self.wbsocket_btn)
        self.Settings_btn = QtWidgets.QPushButton(parent=self.left_btns)
        self.Settings_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.Settings_btn.setMaximumSize(QtCore.QSize(280, 16777215))
        self.Settings_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Settings_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/MainIcons/icons/settingsW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Settings_btn.setIcon(icon8)
        self.Settings_btn.setIconSize(QtCore.QSize(32, 32))
        self.Settings_btn.setCheckable(True)
        self.Settings_btn.setObjectName("Settings_btn")
        self.leftButtons.addButton(self.Settings_btn)
        self.verticalLayout_2.addWidget(self.Settings_btn)
        self.server_btn = QtWidgets.QPushButton(parent=self.left_btns)
        self.server_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.server_btn.setMaximumSize(QtCore.QSize(280, 16777215))
        self.server_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.server_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/MainIcons/icons/serverW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.server_btn.setIcon(icon9)
        self.server_btn.setIconSize(QtCore.QSize(30, 30))
        self.server_btn.setCheckable(True)
        self.server_btn.setObjectName("server_btn")
        self.leftButtons.addButton(self.server_btn)
        self.verticalLayout_2.addWidget(self.server_btn)
        self.verticalLayout.addWidget(self.left_btns, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.menu_btn = QtWidgets.QFrame(parent=self.leftSide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn.sizePolicy().hasHeightForWidth())
        self.menu_btn.setSizePolicy(sizePolicy)
        self.menu_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.menu_btn.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.menu_btn.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_btn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu_btn)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menuButton = QtWidgets.QPushButton(parent=self.menu_btn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuButton.sizePolicy().hasHeightForWidth())
        self.menuButton.setSizePolicy(sizePolicy)
        self.menuButton.setMinimumSize(QtCore.QSize(50, 50))
        self.menuButton.setMaximumSize(QtCore.QSize(50, 50))
        self.menuButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.menuButton.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        self.menuButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/MainIcons/icons/sideBarW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuButton.setIcon(icon10)
        self.menuButton.setIconSize(QtCore.QSize(32, 32))
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout.addWidget(self.menuButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.menu_btn)
        self.horizontalLayout_2.addWidget(self.leftSide)
        self.MainFrame = QtWidgets.QFrame(parent=self.bottonFrame)
        self.MainFrame.setEnabled(True)
        self.MainFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.MainFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MainFrame.setStyleSheet("background-color: rgb(6,6,6);\n"
"border-radius: 8px;")
        self.MainFrame.setObjectName("MainFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.MainFrame)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CentralTabs = QtWidgets.QTabWidget(parent=self.MainFrame)
        self.CentralTabs.setStyleSheet("QTabWidget::pane {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: none;\n"
"    padding: 0px;\n"
"    height: 0px;\n"
"}\n"
"")
        self.CentralTabs.setUsesScrollButtons(True)
        self.CentralTabs.setDocumentMode(False)
        self.CentralTabs.setTabsClosable(False)
        self.CentralTabs.setMovable(False)
        self.CentralTabs.setTabBarAutoHide(False)
        self.CentralTabs.setObjectName("CentralTabs")
        self.terminal_tab = QtWidgets.QWidget()
        self.terminal_tab.setObjectName("terminal_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.terminal_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.terminal_tab)
        self.frame.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutHZ = QtWidgets.QFrame(parent=self.frame)
        self.layoutHZ.setObjectName("layoutHZ")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutHZ)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.console_layout_2 = QtWidgets.QFrame(parent=self.layoutHZ)
        self.console_layout_2.setObjectName("console_layout_2")
        self.console_layout = QtWidgets.QVBoxLayout(self.console_layout_2)
        self.console_layout.setContentsMargins(0, 0, 0, 0)
        self.console_layout.setSpacing(5)
        self.console_layout.setObjectName("console_layout")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.console_layout_2)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono,Helvetica")
        font.setPointSize(-1)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"    selection-background-color:  #FFDAB9;\n"
"    selection-color: black;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"}\n"
"QTextBrowser QScrollBar:vertical {\n"
"    border: 0px;  /* Граница области скролла */\n"
"    background: rgba(0,0,0,0);        /* Фон скроллбара */\n"
"    width: 12px;                /* Ширина вертикального скроллбара */\n"
"    margin: 3px 0 3px 0;      /* Отступы сверху и снизу (чтобы кнопки не обрезались) */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::handle:vertical {\n"
"    border-radius: 3px;\n"
"    background: #111111;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"QTextBrowser QScrollBar::handle:vertical:hover {\n"
"    border-radius: 3px;\n"
"    background: #FFDAB9;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::add-line:vertical {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::sub-line:vertical {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;               /* Убираем границу стрелок */\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;           /* Цвет фона за ползунком */\n"
"}")
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.textBrowser.setObjectName("textBrowser")
        self.console_layout.addWidget(self.textBrowser)
        self.executeLine = QtWidgets.QFrame(parent=self.console_layout_2)
        self.executeLine.setMinimumSize(QtCore.QSize(0, 25))
        self.executeLine.setObjectName("executeLine")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.executeLine)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.com_help_btn = QtWidgets.QPushButton(parent=self.executeLine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.com_help_btn.sizePolicy().hasHeightForWidth())
        self.com_help_btn.setSizePolicy(sizePolicy)
        self.com_help_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.com_help_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.com_help_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WhatsThisCursor))
        self.com_help_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 12px;\n"
"    background-color: rgb(10, 10, 10);\n"
"\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        self.com_help_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/MainIcons/icons/command_helpW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.com_help_btn.setIcon(icon11)
        self.com_help_btn.setIconSize(QtCore.QSize(18, 18))
        self.com_help_btn.setObjectName("com_help_btn")
        self.horizontalLayout_7.addWidget(self.com_help_btn)
        self.LineSenDCommand = QtWidgets.QLineEdit(parent=self.executeLine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LineSenDCommand.sizePolicy().hasHeightForWidth())
        self.LineSenDCommand.setSizePolicy(sizePolicy)
        self.LineSenDCommand.setMinimumSize(QtCore.QSize(0, 25))
        self.LineSenDCommand.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono,Helvetica")
        font.setPointSize(-1)
        self.LineSenDCommand.setFont(font)
        self.LineSenDCommand.setStyleSheet("\n"
"QLineEdit {\n"
"    padding-left: 5px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #111111;\n"
"    qproperty-placeholderText: \"Command prompt\";\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    selection-background-color:  #FFDAB9;\n"
"    selection-color: black;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid #FFDAB9;\n"
"}")
        self.LineSenDCommand.setMaxLength(300)
        self.LineSenDCommand.setObjectName("LineSenDCommand")
        self.horizontalLayout_7.addWidget(self.LineSenDCommand)
        self.send_btn = QtWidgets.QPushButton(parent=self.executeLine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setMinimumSize(QtCore.QSize(50, 25))
        self.send_btn.setMaximumSize(QtCore.QSize(50, 25))
        self.send_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.send_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(10, 10, 10);\n"
"\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        self.send_btn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/MainIcons/icons/sendW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send_btn.setIcon(icon12)
        self.send_btn.setIconSize(QtCore.QSize(20, 20))
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_7.addWidget(self.send_btn)
        self.console_layout.addWidget(self.executeLine)
        self.horizontalLayout_8.addWidget(self.console_layout_2)
        self.lay8 = QtWidgets.QWidget(parent=self.layoutHZ)
        self.lay8.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lay8.setObjectName("lay8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.lay8)
        self.verticalLayout_8.setContentsMargins(0, 1, 1, 1)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.buttons_in_terminal = QtWidgets.QFrame(parent=self.lay8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons_in_terminal.sizePolicy().hasHeightForWidth())
        self.buttons_in_terminal.setSizePolicy(sizePolicy)
        self.buttons_in_terminal.setMinimumSize(QtCore.QSize(200, 153))
        self.buttons_in_terminal.setMaximumSize(QtCore.QSize(200, 16777215))
        self.buttons_in_terminal.setObjectName("buttons_in_terminal")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.buttons_in_terminal)
        self.verticalLayout_6.setContentsMargins(0, 0, 5, 3)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_edit_FSC = QtWidgets.QPushButton(parent=self.buttons_in_terminal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_edit_FSC.sizePolicy().hasHeightForWidth())
        self.button_edit_FSC.setSizePolicy(sizePolicy)
        self.button_edit_FSC.setMinimumSize(QtCore.QSize(200, 36))
        self.button_edit_FSC.setMaximumSize(QtCore.QSize(200, 36))
        self.button_edit_FSC.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_edit_FSC.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_edit_FSC.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"")
        self.button_edit_FSC.setCheckable(False)
        self.button_edit_FSC.setChecked(False)
        self.button_edit_FSC.setObjectName("button_edit_FSC")
        self.verticalLayout_6.addWidget(self.button_edit_FSC)
        self.button_edit_binds = QtWidgets.QPushButton(parent=self.buttons_in_terminal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_edit_binds.sizePolicy().hasHeightForWidth())
        self.button_edit_binds.setSizePolicy(sizePolicy)
        self.button_edit_binds.setMinimumSize(QtCore.QSize(200, 36))
        self.button_edit_binds.setMaximumSize(QtCore.QSize(200, 36))
        self.button_edit_binds.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_edit_binds.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_edit_binds.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"")
        self.button_edit_binds.setCheckable(False)
        self.button_edit_binds.setChecked(False)
        self.button_edit_binds.setObjectName("button_edit_binds")
        self.verticalLayout_6.addWidget(self.button_edit_binds)
        self.button_find_in_console = QtWidgets.QPushButton(parent=self.buttons_in_terminal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_find_in_console.sizePolicy().hasHeightForWidth())
        self.button_find_in_console.setSizePolicy(sizePolicy)
        self.button_find_in_console.setMinimumSize(QtCore.QSize(200, 36))
        self.button_find_in_console.setMaximumSize(QtCore.QSize(200, 36))
        self.button_find_in_console.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_find_in_console.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_find_in_console.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"")
        self.button_find_in_console.setCheckable(True)
        self.button_find_in_console.setChecked(False)
        self.button_find_in_console.setObjectName("button_find_in_console")
        self.verticalLayout_6.addWidget(self.button_find_in_console)
        self.label = QtWidgets.QLabel(parent=self.buttons_in_terminal)
        self.label.setMinimumSize(QtCore.QSize(200, 30))
        self.label.setMaximumSize(QtCore.QSize(200, 20))
        self.label.setStyleSheet("Color: White;\n"
"padding-left: 5px;\n"
"font-size: 14px;")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.verticalLayout_8.addWidget(self.buttons_in_terminal)
        self.fastcoms = QtWidgets.QFrame(parent=self.lay8)
        self.fastcoms.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fastcoms.setObjectName("fastcoms")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.fastcoms)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.fastcoms)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollArea.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 200, 429))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button_term_shlepki = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_term_shlepki.sizePolicy().hasHeightForWidth())
        self.button_term_shlepki.setSizePolicy(sizePolicy)
        self.button_term_shlepki.setMinimumSize(QtCore.QSize(200, 36))
        self.button_term_shlepki.setMaximumSize(QtCore.QSize(200, 36))
        self.button_term_shlepki.setBaseSize(QtCore.QSize(0, 0))
        self.button_term_shlepki.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_term_shlepki.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_term_shlepki.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"")
        self.button_term_shlepki.setCheckable(False)
        self.button_term_shlepki.setChecked(False)
        self.button_term_shlepki.setObjectName("button_term_shlepki")
        self.verticalLayout_10.addWidget(self.button_term_shlepki, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.verticalLayout_8.addWidget(self.fastcoms)
        self.horizontalLayout_8.addWidget(self.lay8)
        self.verticalLayout_5.addWidget(self.layoutHZ)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addWidget(self.frame)
        self.CentralTabs.addTab(self.terminal_tab, "")
        self.stats_tab = QtWidgets.QWidget()
        self.stats_tab.setObjectName("stats_tab")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.stats_tab)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_8 = QtWidgets.QFrame(parent=self.stats_tab)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_18.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_8)
        self.tabWidget.setObjectName("tabWidget")
        self.main_stats_tab = QtWidgets.QWidget()
        self.main_stats_tab.setObjectName("main_stats_tab")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.main_stats_tab)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.tabWidget.addTab(self.main_stats_tab, "")
        self.user_stats_tab = QtWidgets.QWidget()
        self.user_stats_tab.setObjectName("user_stats_tab")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.user_stats_tab)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 5)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.stats_backbutton = QtWidgets.QPushButton(parent=self.user_stats_tab)
        self.stats_backbutton.setMinimumSize(QtCore.QSize(100, 25))
        self.stats_backbutton.setMaximumSize(QtCore.QSize(100, 25))
        self.stats_backbutton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.stats_backbutton.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: rgba(255, 255, 255, 200);\n"
"    font-size: 13px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        self.stats_backbutton.setObjectName("stats_backbutton")
        self.verticalLayout_21.addWidget(self.stats_backbutton)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(15)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.stats_user_icon = QtWidgets.QLabel(parent=self.user_stats_tab)
        self.stats_user_icon.setMinimumSize(QtCore.QSize(100, 100))
        self.stats_user_icon.setMaximumSize(QtCore.QSize(100, 100))
        self.stats_user_icon.setText("")
        self.stats_user_icon.setObjectName("stats_user_icon")
        self.horizontalLayout_19.addWidget(self.stats_user_icon)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.stats_nick = QtWidgets.QLabel(parent=self.user_stats_tab)
        self.stats_nick.setMinimumSize(QtCore.QSize(220, 35))
        self.stats_nick.setMaximumSize(QtCore.QSize(220, 35))
        self.stats_nick.setStyleSheet("Color: White;\n"
"padding-left: 8px;\n"
"font-size: 15px;\n"
"")
        self.stats_nick.setObjectName("stats_nick")
        self.verticalLayout_20.addWidget(self.stats_nick)
        self.stats_status = QtWidgets.QLabel(parent=self.user_stats_tab)
        self.stats_status.setMinimumSize(QtCore.QSize(220, 35))
        self.stats_status.setMaximumSize(QtCore.QSize(220, 35))
        self.stats_status.setStyleSheet("Color: White;\n"
"padding-left: 8px;\n"
"font-size: 13px;\n"
"")
        self.stats_status.setObjectName("stats_status")
        self.verticalLayout_20.addWidget(self.stats_status)
        self.horizontalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_21.addLayout(self.horizontalLayout_19)
        self.verticalLayout_23.addLayout(self.verticalLayout_21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.stats_selectdate = QtWidgets.QCalendarWidget(parent=self.user_stats_tab)
        self.stats_selectdate.setMinimumSize(QtCore.QSize(370, 220))
        self.stats_selectdate.setMaximumSize(QtCore.QSize(370, 220))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono,Helvetica")
        font.setKerning(True)
        self.stats_selectdate.setFont(font)
        self.stats_selectdate.setStyleSheet("QCalendarWidget{\n"
"    background-color: rgb(6,6,6);\n"
"}\n"
"QCalendarWidget QAbstractItemView{\n"
"    color: white;\n"
"    background-color: rgb(6,6,6);\n"
"    alternate-background-color: rgb(6,6,6);\n"
"    selection-background-color: #aaffaa;\n"
"    selection-color: black;\n"
"    border: none;\n"
"}\n"
"QCalendarWidget QAbstractItemView:disabled {\n"
"    color: rgba(255,255,255,100);\n"
"}\n"
"QToolButton {\n"
"    icon-size: 10px, 10px;\n"
"    width: 100px;\n"
"    height: 25px;\n"
"}\n"
"QToolButton#qt_calendar_prevmonth {\n"
"    background-color: rgb(6,6,6);\n"
"    width: 30px;\n"
"    border-radius: 3px;\n"
"    qproperty-icon: url(:/MainIcons/icons/calendar_leftW.png);\n"
"    icon-size: 20px;\n"
"}\n"
"QToolButton#qt_calendar_prevmonth:hover {\n"
"    background: white;\n"
"    qproperty-icon: url(:/MainIcons/icons/calendar_leftB.png);\n"
"}\n"
"QToolButton#qt_calendar_nextmonth {\n"
"    background-color: rgb(6,6,6);\n"
"    width: 30px;\n"
"    border-radius: 3px;\n"
"    qproperty-icon: url(:/MainIcons/icons/calendar_rightW.png);\n"
"    icon-size: 20px;\n"
"}\n"
"QToolButton#qt_calendar_nextmonth:hover {\n"
"    background: white;\n"
"    qproperty-icon: url(:/MainIcons/icons/calendar_rightB.png);\n"
"}\n"
"QToolButton#qt_calendar_monthbutton {\n"
"    background: rgb(6,6,6);\n"
"    font-size: 13px;\n"
"    width: 90px;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_yearbutton {\n"
"    background: rgb(6,6,6);\n"
"    font-size: 14px;\n"
"    width: 90px;\n"
"}\n"
"#qt_calendar_yearedit {\n"
"    width: 90px;\n"
"    selection-color: black;\n"
"    selection-background-color: #FFDAB9;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button, #qt_calendar_yearedit::up-button { \n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"QCalendarWidget QSpinBox#qt_calendar_yearedit {\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"QToolButton#qt_calendar_monthbutton::menu-indicator{\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}")
        self.stats_selectdate.setMinimumDate(QtCore.QDate(2020, 1, 1))
        self.stats_selectdate.setMaximumDate(QtCore.QDate(2100, 12, 31))
        self.stats_selectdate.setGridVisible(False)
        self.stats_selectdate.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.stats_selectdate.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.stats_selectdate.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.stats_selectdate.setNavigationBarVisible(True)
        self.stats_selectdate.setDateEditEnabled(True)
        self.stats_selectdate.setObjectName("stats_selectdate")
        self.horizontalLayout_20.addWidget(self.stats_selectdate)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.stats_total = QtWidgets.QLabel(parent=self.user_stats_tab)
        self.stats_total.setMinimumSize(QtCore.QSize(150, 30))
        self.stats_total.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stats_total.setStyleSheet("Color: White;\n"
"padding-left: 8px;\n"
"font-size: 13px;\n"
"")
        self.stats_total.setObjectName("stats_total")
        self.verticalLayout_22.addWidget(self.stats_total)
        self.stats_total_text = QtWidgets.QLabel(parent=self.user_stats_tab)
        self.stats_total_text.setMinimumSize(QtCore.QSize(150, 150))
        self.stats_total_text.setStyleSheet("Color: White;\n"
"padding-left: 8px;\n"
"font-size: 13px;\n"
"")
        self.stats_total_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.stats_total_text.setObjectName("stats_total_text")
        self.verticalLayout_22.addWidget(self.stats_total_text)
        self.horizontalLayout_20.addLayout(self.verticalLayout_22)
        self.verticalLayout_23.addLayout(self.horizontalLayout_20)
        self.frame_9 = QtWidgets.QFrame(parent=self.user_stats_tab)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.stats_timeline = QtWidgets.QGraphicsView(parent=self.frame_9)
        self.stats_timeline.setMinimumSize(QtCore.QSize(0, 300))
        self.stats_timeline.setMaximumSize(QtCore.QSize(16777215, 300))
        self.stats_timeline.setStyleSheet("QScrollBar:horizontal {\n"
"    border: 0px;  /* Граница области скролла */\n"
"    background: rgba(0,0,0,0);        /* Фон скроллбара */\n"
"    height: 8px;                /* Ширина вертикального скроллбара */\n"
"    margin: 0 3px 0 3px;      /* Отступы сверху и снизу (чтобы кнопки не обрезались) */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    border-radius: 3px;\n"
"    background: #111111;        /* Цвет ползунка */\n"
"    min-width: 10px;           /* Минимальная высота ползунка */\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    border-radius: 3px;\n"
"    background: #FFDAB9;        /* Цвет ползунка */\n"
"    min-width: 10px;           /* Минимальная высота ползунка */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    border: none;               /* Убираем границу стрелок */\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;           /* Цвет фона за ползунком */\n"
"}")
        self.stats_timeline.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.stats_timeline.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.stats_timeline.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.stats_timeline.setObjectName("stats_timeline")
        self.verticalLayout_24.addWidget(self.stats_timeline)
        self.verticalLayout_23.addWidget(self.frame_9)
        self.horizontalLayout_21.addLayout(self.verticalLayout_23)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        self.tabWidget.addTab(self.user_stats_tab, "")
        self.horizontalLayout_18.addWidget(self.tabWidget)
        self.stats_users_frame = QtWidgets.QFrame(parent=self.frame_8)
        self.stats_users_frame.setMinimumSize(QtCore.QSize(240, 0))
        self.stats_users_frame.setMaximumSize(QtCore.QSize(240, 16777215))
        self.stats_users_frame.setObjectName("stats_users_frame")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.stats_users_frame)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.stats_label = QtWidgets.QLabel(parent=self.stats_users_frame)
        self.stats_label.setMinimumSize(QtCore.QSize(240, 20))
        self.stats_label.setMaximumSize(QtCore.QSize(240, 20))
        self.stats_label.setStyleSheet("Color: White;\n"
"padding-left: 5px;\n"
"font-size: 12px;")
        self.stats_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stats_label.setObjectName("stats_label")
        self.verticalLayout_18.addWidget(self.stats_label)
        self.stats_users_scroll = QtWidgets.QScrollArea(parent=self.stats_users_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats_users_scroll.sizePolicy().hasHeightForWidth())
        self.stats_users_scroll.setSizePolicy(sizePolicy)
        self.stats_users_scroll.setMinimumSize(QtCore.QSize(240, 0))
        self.stats_users_scroll.setMaximumSize(QtCore.QSize(240, 16777215))
        self.stats_users_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.stats_users_scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.stats_users_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.stats_users_scroll.setWidgetResizable(True)
        self.stats_users_scroll.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.stats_users_scroll.setObjectName("stats_users_scroll")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 240, 665))
        self.scrollAreaWidgetContents_3.setMinimumSize(QtCore.QSize(240, 0))
        self.scrollAreaWidgetContents_3.setMaximumSize(QtCore.QSize(240, 16777215))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.stats_users_scroll.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_18.addWidget(self.stats_users_scroll)
        self.horizontalLayout_18.addWidget(self.stats_users_frame)
        self.horizontalLayout_17.addWidget(self.frame_8)
        self.CentralTabs.addTab(self.stats_tab, "")
        self.logs_tab = QtWidgets.QWidget()
        self.logs_tab.setObjectName("logs_tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.logs_tab)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.logs_main_frame = QtWidgets.QFrame(parent=self.logs_tab)
        self.logs_main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logs_main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.logs_main_frame.setObjectName("logs_main_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.logs_main_frame)
        self.horizontalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.logs_UMframe = QtWidgets.QFrame(parent=self.logs_main_frame)
        self.logs_UMframe.setObjectName("logs_UMframe")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.logs_UMframe)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.logBrowser = QtWidgets.QTextBrowser(parent=self.logs_UMframe)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono,Helvetica")
        font.setPointSize(-1)
        self.logBrowser.setFont(font)
        self.logBrowser.setStyleSheet("QTextBrowser{\n"
"    selection-background-color:  #FFDAB9;\n"
"    selection-color: black;\n"
"    color: white;\n"
"    font-size: 12px;\n"
"}\n"
"QTextBrowser QScrollBar:vertical{\n"
"    border: 0px; \n"
"    background: rgba(0,0,0,0);\n"
"    width: 12px; \n"
"    margin: 3px 0 3px 0;    \n"
"}\n"
"QTextBrowser QScrollBar:horizontal{\n"
"    border: 0px; \n"
"    background: rgba(0,0,0,0);    \n"
"    height: 12px;              \n"
"    margin: 0 3px 0 3px;    \n"
"}\n"
"\n"
"QTextBrowser QScrollBar::handle:vertical, QScrollBar::handle:horizontal{\n"
"    border-radius: 3px;\n"
"    background: #111111;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"QTextBrowser QScrollBar::handle:vertical:hover , QScrollBar::handle:horizontal:hover{\n"
"    border-radius: 3px;\n"
"    background: #FFDAB9;        /* Цвет ползунка */\n"
"    min-height: 5px;           /* Минимальная высота ползунка */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::add-line:vertical, QScrollBar::add-line:horizontal {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::sub-line:vertical, QScrollBar::sub-line:horizontal {\n"
"    height: 0px;               /* Высота кнопки */\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical, QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"    border: none;               /* Убираем границу стрелок */\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QTextBrowser QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,  QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background: none;           /* Цвет фона за ползунком */\n"
"}")
        self.logBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.logBrowser.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.logBrowser.setObjectName("logBrowser")
        self.verticalLayout_15.addWidget(self.logBrowser)
        self.logs_frame = QtWidgets.QFrame(parent=self.logs_UMframe)
        self.logs_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.logs_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logs_frame.setObjectName("logs_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.logs_frame)
        self.horizontalLayout_12.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.logs_frame2 = QtWidgets.QFrame(parent=self.logs_frame)
        self.logs_frame2.setMinimumSize(QtCore.QSize(0, 50))
        self.logs_frame2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.logs_frame2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logs_frame2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.logs_frame2.setObjectName("logs_frame2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.logs_frame2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.download_log_btn = QtWidgets.QPushButton(parent=self.logs_frame2)
        self.download_log_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.download_log_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.download_log_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.download_log_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        self.download_log_btn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/MainIcons/icons/download_W.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.download_log_btn.setIcon(icon13)
        self.download_log_btn.setIconSize(QtCore.QSize(32, 32))
        self.download_log_btn.setCheckable(False)
        self.download_log_btn.setObjectName("download_log_btn")
        self.horizontalLayout_14.addWidget(self.download_log_btn)
        self.horizontalLayout_12.addWidget(self.logs_frame2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_15.addWidget(self.logs_frame)
        self.horizontalLayout_15.addLayout(self.verticalLayout_15)
        self.logs_frame3 = QtWidgets.QFrame(parent=self.logs_UMframe)
        self.logs_frame3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.logs_frame3.setObjectName("logs_frame3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.logs_frame3)
        self.verticalLayout_16.setContentsMargins(0, 0, 5, 3)
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.logs_text_label = QtWidgets.QLabel(parent=self.logs_frame3)
        self.logs_text_label.setMinimumSize(QtCore.QSize(0, 30))
        self.logs_text_label.setMaximumSize(QtCore.QSize(200, 20))
        self.logs_text_label.setStyleSheet("Color: White;\n"
"padding-left: 5px;\n"
"font-size: 14px;")
        self.logs_text_label.setObjectName("logs_text_label")
        self.verticalLayout_16.addWidget(self.logs_text_label)
        self.logs_level_chooser = QtWidgets.QComboBox(parent=self.logs_frame3)
        self.logs_level_chooser.setMinimumSize(QtCore.QSize(0, 50))
        self.logs_level_chooser.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono,Helvetica")
        font.setPointSize(-1)
        self.logs_level_chooser.setFont(font)
        self.logs_level_chooser.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logs_level_chooser.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.logs_level_chooser.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.logs_level_chooser.setStyleSheet("QComboBox {\n"
"    background-color: #090909;  \n"
"    color: white;           \n"
"    border-radius: 5px;  \n"
"    padding: 5px;              \n"
"    padding-left: 10px;   \n"
"    font-size: 13px;              \n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #111111; \n"
"    border-right: 1px solid #FFDAB9 ; \n"
"    border-left: 1px solid #FFDAB9 ; \n"
"    color: white;  \n"
"    selection-background-color: #FFDAB9; \n"
"    selection-color: black;\n"
"    border-radius: 0px;  \n"
"    padding: 5px;   \n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0px;\n"
"}\n"
"\n"
"QComboBox:open {\n"
"    border-right: 1px solid #FFDAB9 ; \n"
"    border-left: 1px solid #FFDAB9 ; \n"
"    border-radius: 0px;\n"
"}")
        self.logs_level_chooser.setFrame(False)
        self.logs_level_chooser.setObjectName("logs_level_chooser")
        self.logs_level_chooser.addItem("")
        self.verticalLayout_16.addWidget(self.logs_level_chooser)
        self.logs_text_label_2 = QtWidgets.QLabel(parent=self.logs_frame3)
        self.logs_text_label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.logs_text_label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.logs_text_label_2.setStyleSheet("Color: White;\n"
"padding-left: 5px;\n"
"font-size: 12px;")
        self.logs_text_label_2.setObjectName("logs_text_label_2")
        self.verticalLayout_16.addWidget(self.logs_text_label_2)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.logs_frame3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 200, 550))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_16.addWidget(self.scrollArea_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_15.addWidget(self.logs_frame3)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13.addWidget(self.logs_UMframe)
        self.verticalLayout_14.addWidget(self.logs_main_frame)
        self.CentralTabs.addTab(self.logs_tab, "")
        self.websocket_tab = QtWidgets.QWidget()
        self.websocket_tab.setObjectName("websocket_tab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.websocket_tab)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_3 = QtWidgets.QFrame(parent=self.websocket_tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_11.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_5.setMaximumSize(QtCore.QSize(150, 150))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/MainIcons/icons/noconnected.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 160))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_11.setContentsMargins(0, 8, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.layout2 = QtWidgets.QFrame(parent=self.frame_6)
        self.layout2.setObjectName("layout2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layout2)
        self.verticalLayout_12.setContentsMargins(5, 1, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.conect_websc = QtWidgets.QPushButton(parent=self.layout2)
        self.conect_websc.setMinimumSize(QtCore.QSize(280, 50))
        self.conect_websc.setMaximumSize(QtCore.QSize(280, 16777215))
        self.conect_websc.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.conect_websc.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.conect_websc.setStyleSheet("QPushButton{\n"
"    border: 3px solid lime;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(10, 10, 10);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}\n"
"QPushButton:checked{\n"
"    color: black;\n"
"    background-color: #FFDAB9;\n"
"}")
        self.conect_websc.setCheckable(True)
        self.conect_websc.setObjectName("conect_websc")
        self.verticalLayout_12.addWidget(self.conect_websc)
        self.label_6 = QtWidgets.QLabel(parent=self.layout2)
        self.label_6.setMinimumSize(QtCore.QSize(280, 30))
        self.label_6.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.layout2)
        self.label_7.setMinimumSize(QtCore.QSize(280, 30))
        self.label_7.setMaximumSize(QtCore.QSize(280, 16777215))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.horizontalLayout_11.addWidget(self.layout2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_11.addWidget(self.frame_6)
        self.horizontalLayout_9.addWidget(self.frame_3)
        self.CentralTabs.addTab(self.websocket_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.label_4 = QtWidgets.QLabel(parent=self.settings_tab)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 141, 61))
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.CentralTabs.addTab(self.settings_tab, "")
        self.mine_servers = QtWidgets.QWidget()
        self.mine_servers.setObjectName("mine_servers")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.mine_servers)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_7 = QtWidgets.QFrame(parent=self.mine_servers)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_13.addWidget(self.frame_7)
        self.CentralTabs.addTab(self.mine_servers, "")
        self.horizontalLayout_3.addWidget(self.CentralTabs)
        self.horizontalLayout_2.addWidget(self.MainFrame)
        self.verticalLayout_3.addWidget(self.bottonFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.CentralTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RainBot GUI"))
        self.build_info.setText(_translate("MainWindow", "Build: "))
        self.terminal_btn.setText(_translate("MainWindow", "Terminal"))
        self.stats_btn.setText(_translate("MainWindow", "Stats"))
        self.logs_btn.setText(_translate("MainWindow", "logs"))
        self.wbsocket_btn.setText(_translate("MainWindow", "WebSocket"))
        self.Settings_btn.setText(_translate("MainWindow", "Settings"))
        self.server_btn.setText(_translate("MainWindow", "Minecraft servers"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'JetBrains Mono,Helvetica\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.button_edit_FSC.setText(_translate("MainWindow", "Edit fast commands"))
        self.button_edit_binds.setText(_translate("MainWindow", "Edit binds"))
        self.button_find_in_console.setText(_translate("MainWindow", "Find..."))
        self.label.setText(_translate("MainWindow", "Fast Commands:"))
        self.button_term_shlepki.setText(_translate("MainWindow", "Shlepki"))
        self.CentralTabs.setTabText(self.CentralTabs.indexOf(self.terminal_tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_stats_tab), _translate("MainWindow", "Tab 1"))
        self.stats_backbutton.setText(_translate("MainWindow", "Back"))
        self.stats_nick.setText(_translate("MainWindow", "**Nickname"))
        self.stats_status.setText(_translate("MainWindow", "**status"))
        self.stats_total.setText(_translate("MainWindow", "Total:"))
        self.stats_total_text.setText(_translate("MainWindow", "Voice time: \n"
"Mute: \n"
"Full mute: \n"
"Online time: \n"
"Offline time: \n"
"Voice alone: \n"
"AFK time:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user_stats_tab), _translate("MainWindow", "Tab 2"))
        self.stats_label.setText(_translate("MainWindow", "Discord users:"))
        self.CentralTabs.setTabText(self.CentralTabs.indexOf(self.stats_tab), _translate("MainWindow", "Page"))
        self.logBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'JetBrains Mono,Helvetica\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.logs_text_label.setText(_translate("MainWindow", "Logs level:"))
        self.logs_level_chooser.setItemText(0, _translate("MainWindow", "Empty"))
        self.logs_text_label_2.setText(_translate("MainWindow", "Logs:"))
        self.CentralTabs.setTabText(self.CentralTabs.indexOf(self.logs_tab), _translate("MainWindow", "Page"))
        self.conect_websc.setText(_translate("MainWindow", "Connect"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#89b086;\">Connected to:  </span><span style=\" font-weight:600; color:#69c5ca;\">192.168.0.106</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#89b086;\">on port:  </span><span style=\" font-weight:600; color:#69c5ca;\">6789</span></p></body></html>"))
        self.CentralTabs.setTabText(self.CentralTabs.indexOf(self.websocket_tab), _translate("MainWindow", "Page"))
        self.label_4.setText(_translate("MainWindow", "settings"))
        self.CentralTabs.setTabText(self.CentralTabs.indexOf(self.settings_tab), _translate("MainWindow", "Tab 2"))
        self.CentralTabs.setTabText(self.CentralTabs.indexOf(self.mine_servers), _translate("MainWindow", "Page"))
